### ISSUE TITLE
Stopped working after Atom update 1.13.0

### ISSUE THREAD

**Issue by Torniojaws** [msansoni/atom-path-copy#3]
After Atom updated to version 1.13.0, path-copy disappeared from the context menu. It still shows up as installed, but I cannot use it.

Just bringing to attention.

**Comment by msansoni** [comment]
Hello @Torniojaws, it still seems to passing the testing and working on my machines. Would you be able to try reinstalling the package, it may have been corrupted during the update?
Let me know if this doesn't work and I will look into it further.
Mike

**Comment by Torniojaws** [comment]
Thanks. Uninstalling + reinstalling path-copy worked.

**Comment by msansoni** [comment]
Great!
